import { createI18n } from "vue-i18n";

const messages = {
  EN: {
    navbar: {
      title1: "Contact us",
    },
    footer: {
      title1: "Delivering seamless logistics solutions worldwide",
      title2: "Pages",
      title3: "Call now",
      title4: "Email",
      title5: "Location",
      title6: "Newsletter Signup",
      title7:
        "Subscribe to our newsletter to stay updated on our news, promotions, and exclusive offers!",
      title8: "Enter Email",
    },
    home: {
      title1: "Learn more",
      title2: "About us",
      title3: "The main principle of our work is Transparency and reliability",
      title4:
        "The company has direct agreements with agencies of railway, automotive, maritime, and river transport in Turkmenistan. It has also established long-term partnerships with major rolling stock owners and freight forwarders in the CIS countries, the Mediterranean region, and the Baltic states.",
      title5: "Team cohesion and company teamwork",
      title6:
        "Cohesion and teamwork are our core principles. Every team member understands their role and contributes their unique input, ensuring the success of our shared mission.",
      title7: '"Reliability" from the clients\' perspective.',
      title8:
        "Reliability for us means being ready to support the client in any situation, offering solutions, and delivering a high level of service that meets and exceeds expectations.",
      title9: "Licenses and certificates",
      title10: "License for maritime and river transportation",
      title11: "License for maritime and automotive transportation",
      title12: "ISO 9001:2015 Certification",
      title13: "Key values",
      title14: "Our values are the foundation of our success.",
      title15:
        "The company has direct agreements with our values reflecting our principles and aspirations. We uphold honesty, responsibility, and a high level of quality, building strong and trustworthy relationships with our clients and partners.",
      title16: "Trust and recognition from the state",
      title17: "Stability in the company's development",
      title18: "Responsibility for the commitments undertaken.",
      title19: "Modern transport",
      title20: "Our Services",
      title21: "Reliable Sea Freight",
      title22: "Ground Transportation",
      title23: "Swift And Efficient Air Cargo",
      title24: "Years of experience",
      title25: "Cargo delivered",
      title26: "Satisfied clients",
      title27: "Warehouses",
      title28: "Main types of cargo transported",
      title29: "Household and computing equipment",
      title30: "Medicine and pharmaceuticals",
      title31: "Production lines and equipment",
      title32: "Seeds and plants",
      title33: "Agricultural machinery",
      title34: "Chemical industry (sulfur, urea, polypropylene)",
      title35: "Textiles",
      title36: "Food products",
    },
    about: {
      title1: "Home",
      title2: "Core Values",
      title3: "Employee cohesion and teamwork within the company",
      title4: '"Reliability" from the clients\' perspective.',
      title5: "Trust and recognition from the government.",
      title6: "Stability in the company's development.",
      title7: "Responsibility for the commitments made.",
      title8: "Modern transport",
      title9:
        "Guarantee of safety in the transportation of all types of cargo.",
    },
    service: {
      title1: "Service",
      title2: "The Safest Shipping Service In Turkmenistan",
      title3: "Easy Shipment",
      title4: "Secure Delivery",
      title5: "Fast Arrival",
      title6: "Services We provide",
    },
    contact: {
      title1: "Full name",
      title2: "Phone number",
      title3: "Message",
      title4: "Send",
    },
  },
  RU: {
    navbar: {
      title1: "Свяжитесь с нами",
    },
    footer: {
      title1: "Предоставляем бесшовные логистические решения по всему миру",
      title2: "Страницы",
      title3: "Позвоните сейчас",
      title4: "Электронная почта",
      title5: "Местоположение",
      title6: "Подписка на рассылку",
      title7:
        "Подпишитесь на нашу рассылку, чтобы быть в курсе новостей, акций и эксклюзивных предложений!",
      title8: "Введите Email",
    },
    home: {
      title1: "Узнать больше",
      title2: "О нас",
      title3: "Основной принцип нашей работы — прозрачность и надежность",
      title4:
        "Компания имеет прямые соглашения с агентствами железнодорожного, автомобильного, морского и речного транспорта в Туркменистане. Также установлены долгосрочные партнерства с крупными владельцами подвижного состава и экспедиторами в странах СНГ, Средиземноморье и странах Балтики.",
      title5: "Согласованность команды и командная работа компании",
      title6:
        "Согласованность и командная работа — наши основные принципы. Каждый член команды понимает свою роль и вносит свой уникальный вклад, что обеспечивает успех нашей общей миссии.",
      title7: '"Надежность" с точки зрения клиентов.',
      title8:
        "Надежность для нас означает готовность поддержать клиента в любой ситуации, предложить решения и предоставить высокий уровень обслуживания, который соответствует и превышает ожидания.",
      title9: "Лицензии и сертификаты",
      title10: "Лицензия на морские и речные перевозки",
      title11: "Лицензия на морские и автомобильные перевозки",
      title12: "Сертификат ISO 9001:2015",
      title13: "Ключевые ценности",
      title14: "Наши ценности — основа нашего успеха.",
      title15:
        "Компания имеет прямые соглашения с нашими ценностями, отражающими наши принципы и стремления. Мы поддерживаем честность, ответственность и высокий уровень качества, строя крепкие и доверительные отношения с нашими клиентами и партнерами.",
      title16: "Доверие и признание со стороны государства",
      title17: "Стабильность в развитии компании",
      title18: "Ответственность за взятые на себя обязательства.",
      title19: "Современный транспорт",
      title20: "Наши услуги",
      title21: "Надежные морские перевозки",
      title22: "Наземные перевозки",
      title23: "Быстрая и эффективная воздушная доставка",
      title24: "Годы опыта",
      title25: "Доставленный груз",
      title26: "Довольные клиенты",
      title27: "Склады",
      title28: "Основные виды перевозимого груза",
      title29: "Бытовая и вычислительная техника",
      title30: "Медицина и фармацевтика",
      title31: "Производственные линии и оборудование",
      title32: "Семена и растения",
      title33: "Сельскохозяйственная техника",
      title34: "Химическая промышленность (сера, мочевина, полипропилен)",
      title35: "Текстиль",
      title36: "Продукты питания",
    },
    about: {
      title1: "Главная",
      title2: "Основные ценности",
      title3: "Сплоченность сотрудников и командная работа в компании",
      title4: '"Надежность" с точки зрения клиентов.',
      title5: "Доверие и признание со стороны государства.",
      title6: "Стабильность в развитии компании.",
      title7: "Ответственность за взятые обязательства.",
      title8: "Современный транспорт",
      title9: "Гарантия безопасности при перевозке всех видов грузов.",
    },
    service: {
      title1: "Услуги",
      title2: "Самая безопасная служба доставки в Туркменистане",
      title3: "Простая отправка",
      title4: "Надежная доставка",
      title5: "Быстрое прибытие",
      title6: "Услуги, которые мы предоставляем",
    },
    contact: {
      title1: "Полное имя",
      title2: "Номер телефона",
      title3: "Сообщение",
      title4: "Отправить",
    },
  },
  TM: {
    navbar: {
      title1: "Biz bilen habarlaşyň",
    },
    footer: {
      title1:
        "Dünýä ýüzünde päsgelçiliksiz logistika çözgütlerini hödürleýäris",
      title2: "Sahypalar",
      title3: "Habarlaşmak",
      title4: "E-poçta",
      title5: "Ýerleşýän ýeri",
      title6: "Habarnama ýazylyň",
      title7:
        "Täzeliklerimizden, mahabatlardan we aýratyn tekliplerimizden habarly bolmak üçin habarnama ýazylyň!",
      title8: "E-poçta giriziň",
    },
    home: {
      title1: "Dowamyny oka",
      title2: "Biz barada",
      title3: "Işimiziň esasy maksady: Açyklyk we ynamlylyk",
      title4:
        "Kärhananyň Türkmenistandaky demirýol, awtoulag, deňiz we derýa ulag agentlikleri bilen aragatnaşyklary bar. Şeýle hem, BSG ýurtlarynda, Ortaýer sebitinde we Baltika döwletlerinde uly ulag ätiýaçlyklary we ýük göterijiler bilen uzakmöhletli hyzmatdaşlyklar guruldy.",
      title5: "Toparyň jebisligi we kärhananyň toparçylyk işleri",
      title6:
        "Jebislik we toparçylyk — biziň esasy prinsiplerimizdir. Her bir topar agzasy öz roluny düşünýär we özboluşly goşantyny goşýar, bu bolsa umumy missiýamyzy üstünlikli amala aşyrmaga mümkinçilik berýär.",
      title7: '"Ynamsyzlyk" müşderileriň perspektiwasyndan.',
      title8:
        "Ynamsyzlyk biziň üçin müşderini her ýagdaýda goldamaga, çözgütler teklip etmaga we ýokary derejeli hyzmaty hödürlemäge taýýar bolmakdyr, bu bolsa umytlaryndan ýokarydyr.",
      title9: "Lisenziýalar we sertifikatlar",
      title10: "Deňiz we derýa ulaglary üçin lisenziýa",
      title11: "Deňiz we awtoulag ulaglary üçin lisenziýa",
      title12: "ISO 9001:2015 Sertifikaty",
      title13: "Başlyca gymmatlyklarymyz",
      title14: "Biziň gymmatlyklarymyz üstünligimiziň binýady bolup durýar.",
      title15:
        "Kärhana biziň gymmatlyklarymyzyň esasy prinsiplerimizi we maksatlarymyzy beýan edýär. Biz halallygy, jogapkärçiligi we ýokary hil derejesini goldaýarys, müşderilerimiz we hyzmatdaşlarymyz bilen ygtybarly we ygtybarly gatnaşyklaryň ýola goýulmagyna ýardam berýäris.",
      title16: "Döwlet tarapyndan bolan ynam we tanalma",
      title17: "Kärhananyň ösüşindäki durnuklylyk",
      title18: "Göterilen borçlar üçin jogapkärçilik.",
      title19: "Zamanyň talabyna laýyk ulag",
      title20: "Hyzmatlarymyz",
      title21: "Ynançly Deňiz Ýükleri",
      title22: "Ýerüsti Ulaglar",
      title23: "Çalt we täsirli howa ýükleri",
      title24: "Şahsy tejribe ýyllary",
      title25: "Görnüşli ýükler",
      title26: "Satyşly müşderiler",
      title27: "Ammarlar",
      title28: "Daşalýan esasy ýükler",
      title29: "Hojalyk we kompýuter enjamlary",
      title30: "Derman we farmasewtika önümleri",
      title31: "Önümçilik liniýalary we enjamlar",
      title32: "Tohumlar we ösümlikler",
      title33: "Agrar tehnika",
      title34: "Himiýa senagaty (gümüş, üre, polipropilen)",
      title35: "Tekstiller",
      title36: "Azyk önümleri",
    },
    about: {
      title1: "Baş sahypa",
      title2: "Esasy gymmatlyklar",
      title3: "Kärhanada işgärleriň jebisligi we toparlaýyn işi",
      title4: '"Ynamsyzlyk" müşderileriň perspektiwasyndan.',
      title5: "Döwlet tarapyndan ynam we tanalma.",
      title6: "Kärhananyň ösüşindäki durnuklylyk.",
      title7: "Ugradylan ýükleriň ýerine ýetirilmegine jogapkärçilik.",
      title8: "Zamana laýyk ulag",
      title9: "Her dürli ýüküň daşalmagynyň howpsuzlygyna kepillik.",
    },
    service: {
      title1: "Hyzmatlar",
      title2: "Türkmenistandaky iň ygtybarly ýük daşama hyzmaty",
      title3: "Ýönekeý ýük daşama",
      title4: "Howpsuz eltip bermek",
      title5: "Çalt barş",
      title6: "Berýän hyzmatlarymyz",
    },
    contact: {
      title1: "Doly ady",
      title2: "Telefon belgisi",
      title3: "Habar",
      title4: "Ugratmak",
    },
  },
};

export const i18n = createI18n({
  locale: "TM",
  fallbackLocale: "TM",
  messages,
});
